  export const NSFW =[
    {"name":"twochainz1","artist":"2 chainz","track":"2chainz_yeah2.ogg","img":"2chainz.png"},
    {"name":"twochainz2","artist":"2 chainz","track":"2chainz_4.ogg","img":"2chainz.png"},
    {"name":"twochainz3","artist":"2 chainz","track":"2chainz_tellem.ogg","img":"2chainz.png"},
    {"name":"twochainz4","artist":"2 chainz","track":"2chainz_tru.ogg","img":"2chainz.png"},
    {"name":"twochainz5","artist":"2 chainz","track":"2chainz_unh3.ogg","img":"2chainz.png"},
    {"name":"twochainz6","artist":"2 chainz","track":"2chainz_watchout.ogg","img":"2chainz.png"},
    {"name":"twochainz7","artist":"2 chainz","track":"2chainz_whistle.ogg","img":"2chainz.png"},
    {"name":"tupac","artist":"2pac","track":"2pac_4.ogg","img":"2pac.png"},
    {"name":"tupac","artist":"2pac","track":"2pac_5.ogg","img":"2pac.png"},
    {"name":"fiftycent","artist":"50 Cent","track":"50_5.ogg","img":"fiftycent.png"},
    {"name":"actionbronson","artist":"Action Bronson","track":"action_bronsolino.ogg","img":"actionbronson.png"},
    {"name":"akon","artist":"Akon","track":"akon_1.ogg","img":"akon.png"},
    {"name":"bigboi","artist":"Big Boi","track":"bigboi_1.ogg","img":"bigboi.png"},
    {"name":"bigsean1","artist":"Big Sean","track":"bigsean_boi2.ogg","img":"bigsean.png"},
    {"name":"bigsean2","artist":"Big Sean","track":"bigsean_holdup2.ogg","img":"bigsean.png"},
    {"name":"bigsean3","artist":"Big Sean","track":"bigsean_ohgod.ogg","img":"bigsean.png"},
    {"name":"birdman1","artist":"Birdman","track":"birdman_4.ogg","img":"birdman.png"},
    {"name":"birdman2","artist":"Birdman","track":"birdman_10.ogg","img":"birdman.png"},
    {"name":"bobbyshmurda","artist":"Bobby Shmurda","track":"bobby_hahaha.ogg","img":"bobby.png"},
    {"name":"bowwow","artist":"Bow Wow","track":"bowwow_yeah.ogg","img":"bowwow.png"},
    {"name":"bunb","artist":"Bun B","track":"bunb_ugk4life.ogg","img":"bunb.png"},
    {"name":"busta","artist":"Busta Rhymes","track":"busta_6.ogg","img":"busta.png"},
    {"name":"camron","artist":"Cam'Ron","track":"camron_1.ogg","img":"camron.png"},
    {"name":"chance","artist":"Chance The Rapper","track":"chance_aghh2.ogg","img":"chance.png"},
    {"name":"chingy","artist":"Chingy","track":"chingy_1.ogg","img":"chingy.png"},
    {"name":"currensy","artist":"Curren$y","track":"currensy_1.ogg","img":"currensy.png"},
    {"name":"dabrat1","artist":"Da Brat","track":"dabrat_comeon.ogg","img":"dabrat.png"},
    {"name":"dabrat2","artist":"Da Brat","track":"dabrat_lookout.ogg","img":"dabrat.png"},
    {"name":"dabrat3","artist":"Da Brat","track":"dabrat_oh.ogg","img":"dabrat.png"},
    {"name":"dannybrown","artist":"Danny Brown","track":"danny_stop.ogg", "img": "dannybrown.png"},
    {"name":"davidbanner","artist":"David Banner","track":"davidbanner_5.ogg","img":"davidbanner.png"},
    {"name":"desiigner1","artist":"Desiigner","track":"desiigner_pandapanda.ogg","img":"desiigner.png"},
    {"name":"desiigner2","artist":"Desiigner","track":"desiigner_rahhh.ogg","img":"desiigner.png"},
    {"name":"desiigner3","artist":"Desiigner","track":"desiigner_yeha.ogg","img":"desiigner.png"},
    {"name":"diddy","artist":"Diddy","track":"diddy_1.ogg", "img": "diddy.png"},
    {"name":"dizzee","artist":"Dizzee Rascal","track":"dizzee_1.ogg","img":"dizzee.png"},
    {"name":"khaled1","artist":"DJ Khaled","track":"djkhaled_2.ogg","img":"khaled.png"},
    {"name":"khaled2","artist":"DJ Khaled","track":"djkhaled_3.ogg","img":"khaled.png"},
    {"name":"djpaul1","artist":"DJ Paul","track":"djpaul_2.ogg","img":"djpaul.png"},
    {"name":"djpaul2","artist":"DJ Paul","track":"djpaul_3.ogg","img":"djpaul.png"},
    {"name":"djpaul3","artist":"DJ Paul","track":"djpaul_9.ogg","img":"djpaul.png"},
    {"name":"dmx1","artist":"DMX","track":"dmx_1.ogg","img":"dmx.png"},
    {"name":"dmx2","artist":"DMX","track":"dmx_3.ogg","img":"dmx.png"},
    {"name":"dmx3","artist":"DMX","track":"dmx_6.ogg","img":"dmx.png"},
    {"name":"dmx4","artist":"DMX","track":"dmx_7.ogg","img":"dmx.png"},
    {"name":"drake1","artist":"Drake","track":"drake_2.ogg","img":"drake.png"},
    {"name":"drake2","artist":"Drake","track":"drake_3.ogg","img":"drake.png"},
    {"name":"drake3","artist":"Drake","track":"drake_4.ogg","img":"drake.png"},
    {"name":"drake4","artist":"Drake","track":"drake_5.ogg","img":"drake.png"},
    {"name":"drake5","artist":"Drake","track":"drake_goddamngoddamn.ogg","img":"drake.png"},
    {"name":"drake6","artist":"Drake","track":"drake_worst.ogg","img":"drake.png"},
    {"name":"drummaboy","artist":"Drumma Boy","track":"drummaboy_1.ogg","img":"drummaboy.png"},
    {"name":"e401","artist":"E-40","track":"e40_1.ogg","img":"e40.png"},
    {"name":"e402","artist":"E-40","track":"e40_2.ogg","img":"e40.png"},
    {"name":"eazye","artist":"Eazy-E","track":"eazye_1.ogg","img":"eazye.png"},
    {"name":"eminem1","artist":"Eminem","track":"eminem_3.ogg","img":"eminem.png"},
    {"name":"eminem2","artist":"Eminem","track":"eminem_4.ogg","img":"eminem.png"},
    {"name":"fatjoe1","artist":"Fat Joe","track":"fatjoe_1.ogg","img":"fatjoe.png"},
    {"name":"fatjoe2","artist":"Fat Joe","track":"fatjoe_9.ogg","img":"fatjoe.png"},
    {"name":"fatjoe3","artist":"Fat Joe","track":"fatjoe_5.ogg","img":"fatjoe.png"},
    {"name":"fettywap","artist":"Fetty Wap","track":"fetty_1738.ogg","img":"fetty.png"},
    {"name":"flava","artist":"Flavor Flav","track":"flava_1.ogg","img":"flava.png"},
    {"name":"freeway","artist":"Freeway","track":"freeway_1.ogg","img":"freeway.png"},
    {"name":"frenchie","artist":"French Montana","track":"french_1.ogg","img":"frenchie.png"},
    {"name":"future1","artist":"Future","track":"future_brrr.ogg","img":"future.png"},
    {"name":"future2","artist":"Future","track":"future_hendrix.ogg","img":"future.png"},
    {"name":"future3","artist":"Future","track":"future_hey.ogg","img":"future.png"},
    {"name":"future4","artist":"Future","track":"future_woo.ogg","img":"future.png"},
    {"name":"ghostface","artist":"Ghostface Killah","track":"ghostface_yo.ogg","img":"ghostface.png"},
    {"name":"grandmaster","artist":"Grandmaster Flash","track":"grandmaster_1.ogg","img":"grandmaster.png"},
    {"name":"gucci1","artist":"Gucci Mane","track":"gucci_1.ogg","img":"gucci.png"},
    {"name":"gucci2","artist":"Gucci Mane","track":"gucci_4.ogg","img":"gucci.png"},
    {"name":"gucci3","artist":"Gucci Mane","track":"gucci_14.ogg","img":"gucci.png"},
    {"name":"gucci4","artist":"Gucci Mane","track":"gucci_8.ogg","img":"gucci.png"},
    {"name":"gucci5","artist":"Gucci Mane","track":"gucci_9.ogg","img":"gucci.png"},
    {"name":"hurricane","artist":"Hurricane Chris","track":"hurricanechris_1.ogg","img":"hurricane.png"},
    {"name":"icecube","artist":"Ice Cube","track":"icecube_1.ogg","img":"icecube.png"},
    {"name":"inspectahdeck","artist":"Inspectah Deck","track":"inspectahdeck_killahill.ogg","img":"inspectahdeck.png"},
    {"name":"jadakiss","artist":"Jadakiss","track":"jadakiss_3.ogg","img":"jadakiss.png"},
    {"name":"jarule1","artist":"Ja Rule","track":"jarule_1.ogg","img":"jarule.png"},
    {"name":"jarule2","artist":"Ja Rule","track":"jarule_2.ogg","img":"jarule.png"},
    {"name":"jayz1","artist":"Jay-Z","track":"jayz_7.ogg","img":"jayz.png"},
    {"name":"jayz2","artist":"Jay-Z","track":"jayz_9.ogg","img":"jayz.png"},
    {"name":"jayz3","artist":"Jay-Z","track":"jayz_1.ogg","img":"jayz.png"},
    {"name":"jayz4","artist":"Jay-Z","track":"jayz5.ogg","img":"jayz.png"},
    {"name":"jayz5","artist":"Jay-Z","track":"jayz7.ogg","img":"jayz.png"},
    {"name":"jayz6","artist":"Jay-Z","track":"jayz8.ogg","img":"jayz.png"},
    {"name":"jayz7","artist":"Jay-Z","track":"jayz_itsthero.ogg","img":"jayz.png"},
    {"name":"jayz8","artist":"Jay-Z","track":"jayz_itsyoboy.ogg","img":"jayz.png"},
    {"name":"jayz9","artist":"Jay-Z","track":"jayz_jiggaman.ogg","img":"jayz.png"},
    {"name":"jayz10","artist":"Jay-Z","track":"jayz_woo.ogg","img":"jayz.png"},
    {"name":"jayz11","artist":"Jay-Z","track":"jayz_yessir.ogg","img":"jayz.png"},
    {"name":"jayz12","artist":"Jay-Z","track":"jayz_young.ogg","img":"jayz.png"},
    {"name":"jcole","artist":"J. Cole","track":"jcole_bitch.ogg","img":"jcole.png"},
    {"name":"jd","artist":"Jermaine Dupri","track":"jermaine_unh.ogg","img":"jd.png"},
    {"name":"jimjones1","artist":"Jim Jones","track":"jones_8.ogg","img":"jimjones.png"},
    {"name":"jimjones2","artist":"Jim Jones","track":"jones_14.ogg","img":"jimjones.png"},
    {"name":"juelz","artist":"Juelz Santana","track":"juelz_2.ogg","img":"juelz.png"},
    {"name":"juicyj1","artist":"Juicy J","track":"juicyj_1.ogg","img":"juicyj.png"},
    {"name":"juicyj2","artist":"Juicy J","track":"juicyj_8.ogg","img":"juicyj.png"},
    {"name":"juicyj3","artist":"Juicy J","track":"juicyj_9.ogg","img":"juicyj.png"},
    {"name":"juicyj4","artist":"Juicy J","track":"juicyj_10.ogg","img":"juicyj.png"},
    {"name":"juicyj5","artist":"Juicy J","track":"juicyj_7.ogg","img":"juicyj.png"},
    {"name":"kendrick1","artist":"Kendrick Lamar","track":"kendrick_biatch3.ogg","img":"kendrick.png"},
    {"name":"kendrick2","artist":"Kendrick Lamar","track":"kendrick_tootoo.ogg","img":"kendrick.png"},
    {"name":"kanye","artist":"Kanye West","track":"kanye_1.ogg","img":"kanye.png"},
    {"name":"killermike1","artist":"Killer Mike","track":"killermike_2.ogg","img":"killermike.png"},
    {"name":"killermike2","artist":"Killer Mike","track":"killermike_3.ogg","img":"killermike.png"},
    {"name":"krsone","artist":"KRS One","track":"krsone_1.ogg","img":"krsone.png"},
    {"name":"lilb1","artist":"Lil B","track":"lilb_1.ogg","img":"lilb.png"},
    {"name":"lilb2","artist":"Lil B","track":"lilb_2.ogg","img":"lilb.png"},
    {"name":"liljon1","artist":"Lil Jon","track":"liljon_2.ogg","img":"liljon.png"},
    {"name":"liljon2","artist":"Lil Jon","track":"liljon_3.ogg","img":"liljon.png"},
    {"name":"lilkim1","artist":"Lil Kim","track":"lilkim_queenb.ogg","img":"lilkim.png"},
    {"name":"lilkim2","artist":"Lil Kim","track":"lilkim_uhunh.ogg","img":"lilkim.png"},
    {"name":"liluzivert","artist":"Lil Uzi Vert","track":"liluzivert_yah2.ogg","img":"liluzivert.png"},
    {"name":"weezy1","artist":"Lil Wayne","track":"weezy_22.ogg","img":"weezy.png"},
    {"name":"weezy2","artist":"Lil Wayne","track":"weezy_25.ogg","img":"weezy.png"},
    {"name":"weezy3","artist":"Lil Wayne","track":"weezy_31.ogg","img":"weezy.png"},
    {"name":"yachty","artist":"Lil Yachty","track":"lilyachty_lilboat.ogg","img":"lilyachty.png"},
    {"name":"ludacris","artist":"Ludacris","track":"ludacris_2.ogg","img":"ludacris.png"},
    {"name":"madeintyo","artist":"Madeintyo","track":"madeintyo_skrrskrr.ogg","img":"madeintyo.png"},
    {"name":"mannie","artist":"Mannie Fresh","track":"mannie_2.ogg","img":"mannie.png"},
    {"name":"mchammer","artist":"MC Hammer","track":"mchammer_1.ogg","img":"mchammer.png"},
    {"name":"methodman","artist":"Method Man","track":"methodman_1.ogg","img":"methodman.png"},
    {"name":"metroboomin","artist":"Metro Boomin","track":"metro_somemo.ogg","img":"metroboomin.png"},
    {"name":"mikejones","artist":"Mike Jones","track":"mikejones_2.ogg","img":"mikejones.png"},
    {"name":"nas","artist":"Nas","track":"nas_6.ogg","img":"nas.png"},
    {"name":"natedogg","artist":"Nate Dogg","track":"natedogg_1.ogg","img":"natedogg.png"},
    {"name":"nicki","artist":"Nicki Minaj","track":"nicki_youngmoney.ogg","img":"nicki.png"},
    {"name":"biggie","artist":"The Notorious B.I.G.","track":"biggie_2.ogg","img":"biggie.png"},
    {"name":"oj","artist":"OJ Da Juiceman","track":"oj_4.ogg","img":"oj.png"},
    {"name":"odb","artist":"Ol Dirty Bastard","track":"odb_shimmy.ogg","img":"odb.png"},
    {"name":"pharrell1","artist":"Pharrell","track":"pharrell_1.ogg","img":"pharrell.png"},
    {"name":"pharrell2","artist":"Pharrell","track":"pharrell_2.ogg","img":"pharrell.png"},
    {"name":"pimpc1","artist":"Pimp C","track":"pimpc_1.ogg","img":"pimpc.png"},
    {"name":"pimpc2","artist":"Pimp C","track":"pimpc_sweetjones3.ogg","img":"pimpc.png"},
    {"name":"pitbull1","artist":"Pitbull","track":"pitbull_1.ogg","img":"pitbull.png"},
    {"name":"pitbull2","artist":"Pitbull","track":"pitbull_2.ogg","img":"pitbull.png"},
    {"name":"pitbull3","artist":"Pitbull","track":"pitbull_6.ogg","img":"pitbull.png"},
    {"name":"projectpat","artist":"Project Pat","track":"projectpat_1.ogg","img":"projectpat.png"},
    {"name":"pushat1","artist":"Pusha T","track":"pushat_1.ogg","img":"pushat.png"},
    {"name":"pushat2","artist":"Pusha T","track":"pushat_haha.ogg","img":"pushat.png"},
    {"name":"pushat3","artist":"Pusha T","track":"pushat_unh.ogg","img":"pushat.png"},
    {"name":"takeof","artist":"Takeoff","track":"takeoff_bitch.ogg","img":"takeoff.png"},
    {"name":"raekwon","artist":"Raekwon","track":"raekwon_yo.ogg","img":"raekwon.png"},
    {"name":"redman","artist":"Redman","track":"redman_heyo.ogg","img":"redman.png"},
    {"name":"ross1","artist":"Rick Ross","track":"ross_1.ogg","img":"ross.png"},
    {"name":"ross2","artist":"Rick Ross","track":"ross_2.ogg","img":"ross.png"},
    {"name":"ross3","artist":"Rick Ross","track":"ross_4.ogg","img":"ross.png"},
    {"name":"ross3","artist":"Rick Ross","track":"ross_woo.ogg","img":"ross.png"},
    {"name":"schoolboyq","artist":"Schoolboy Q","track":"schoolboy_yawk.ogg","img":"schoolboyq.png"},
    {"name":"snoop1","artist":"Snoop Dogg","track":"snoop_5.ogg","img":"snoop.png"},
    {"name":"snoop2","artist":"Snoop Dogg","track":"snoop_4.ogg","img":"snoop.png"},
    {"name":"snoop3","artist":"Snoop Dogg","track":"snoop_1.ogg","img":"snoop.png"},
    {"name":"soulja1","artist":"Soulja Boy","track":"soulja_4.ogg","img":"soulja.png"},
    {"name":"soulja2","artist":"Soulja Boy","track":"soulja_5.ogg","img":"soulja.png"},
    {"name":"swizz","artist":"Swizz Beatz","track":"swizz_1.ogg","img":"swizz.png"},
    {"name":"ti1","artist":"T.I.","track":"ti_5.ogg","img":"ti.png"},
    {"name":"ti2","artist":"T.I.","track":"ti_22.ogg","img":"ti.png"},
    {"name":"tpain1","artist":"T-Pain","track":"tpain_2.ogg", "img":"tpain.png"},
    {"name":"tpain2","artist":"T-Pain","track":"tpain1.ogg","img":"tpain.png"},
    {"name":"treysongz","artist":"Trey Songz","track":"treysongz_4.ogg","img":"treysongz.png"},
    {"name":"trickdaddy1","artist":"Trick Daddy","track":"trick_1.ogg","img":"trickdaddy.png"},
    {"name":"trickdaddy2","artist":"Trick Daddy","track":"trick_2.ogg","img":"trickdaddy.png"},
    {"name":"trickdaddy3","artist":"Trick Daddy","track":"trick_4.ogg","img":"trickdaddy.png"},
    {"name": "twentyonesavage", "artist": "21 Savage", "track": "21savage_21.ogg", "img": "21savage.png"},
    {"name":"tyga","artist":"Tyga","track":"tyga_unh.ogg","img":"tyga.png"},
    {"name":"waka1","artist":"Waka Flocka Flame","track":"waka_1.ogg","img":"waka.png"},
    {"name":"waka2","artist":"Waka Flocka Flame","track":"waka_8.ogg","img":"waka.png"},
    {"name":"willsmith1","artist":"Will Smith","track":"willsmith_1.ogg","img":"willsmith.png"},
    {"name":"willsmith2","artist":"Will Smith","track":"willsmith_2.ogg","img":"willsmith.png"},
    {"name":"wiz1","artist":"Wiz Khalifa","track":"wiz_1.ogg","img":"wiz.png"},
    {"name":"wiz2","artist":"Wiz Khalifa","track":"wiz_unh.ogg","img":"wiz.png"},
    {"name":"jeezy1","artist":"Young Jeezy","track":"jeezy_10.ogg","img":"jeezy.png"},
    {"name":"jeezy3","artist":"Young Jeezy","track":"jeezy_1.ogg","img":"jeezy.png"},
    {"name":"quavo","artist":"Quavo","track":"quavo_youngnigga.ogg","img":"quavo.png"},
    {"name":"takeoff","artist":"Takeoff","track":"takeoff_bitch.ogg","img":"takeoff.png"},
    {"name":"trapaholics","artist":"Trapaholics","track":"trapaholics_damnson.ogg","img":"trapaholics.png"},
    ]
  
  export const SFW =[
  {"name":"twochainz1","artist":"2 chainz","track":"2chainz_yeah2.ogg","img":"2chainz.png"},
  {"name":"twochainz2","artist":"2 chainz","track":"2chainz_4.ogg","img":"2chainz.png"},
  {"name":"twochainz3","artist":"2 chainz","track":"2chainz_tellem.ogg","img":"2chainz.png"},
  {"name":"twochainz4","artist":"2 chainz","track":"2chainz_tru.ogg","img":"2chainz.png"},
  {"name":"twochainz5","artist":"2 chainz","track":"2chainz_unh3.ogg","img":"2chainz.png"},
  {"name":"twochainz7","artist":"2 chainz","track":"2chainz_whistle.ogg","img":"2chainz.png"},
  {"name":"tupac","artist":"2pac","track":"2pac_4.ogg","img":"2pac.png"},
  {"name":"fiftycent","artist":"50 Cent","track":"50_5.ogg","img":"fiftycent.png"},
  {"name":"actionbronson","artist":"Action Bronson","track":"action_bronsolino.ogg","img":"actionbronson.png"},
  {"name":"akon","artist":"Akon","track":"akon_1.ogg","img":"akon.png"},
  {"name":"bigboi","artist":"Big Boi","track":"bigboi_1.ogg","img":"bigboi.png"},
  {"name":"bigsean1","artist":"Big Sean","track":"bigsean_boi2.ogg","img":"bigsean.png"},
  {"name":"bigsean2","artist":"Big Sean","track":"bigsean_holdup2.ogg","img":"bigsean.png"},
  {"name":"bigsean3","artist":"Big Sean","track":"bigsean_ohgod.ogg","img":"bigsean.png"},
  {"name":"birdman1","artist":"Birdman","track":"birdman_4.ogg","img":"birdman.png"},
  {"name":"birdman2","artist":"Birdman","track":"birdman_10.ogg","img":"birdman.png"},
  {"name":"bobbyshmurda","artist":"Bobby Shmurda","track":"bobby_hahaha.ogg","img":"bobby.png"},
  {"name":"bowwow","artist":"Bow Wow","track":"bowwow_yeah.ogg","img":"bowwow.png"},
  {"name":"bunb","artist":"Bun B","track":"bunb_ugk4life.ogg","img":"bunb.png"},
  {"name":"busta","artist":"Busta Rhymes","track":"busta_6.ogg","img":"busta.png"},
  {"name":"camron","artist":"Cam'Ron","track":"camron_1.ogg","img":"camron.png"},
  {"name":"chance","artist":"Chance The Rapper","track":"chance_aghh2.ogg","img":"chance.png"},
  {"name":"chingy","artist":"Chingy","track":"chingy_1.ogg","img":"chingy.png"},
  {"name":"currensy","artist":"Curren$y","track":"currensy_1.ogg","img":"currensy.png"},
  {"name":"dabrat1","artist":"Da Brat","track":"dabrat_comeon.ogg","img":"dabrat.png"},
  {"name":"dabrat2","artist":"Da Brat","track":"dabrat_lookout.ogg","img":"dabrat.png"},
  {"name":"dabrat3","artist":"Da Brat","track":"dabrat_oh.ogg","img":"dabrat.png"},
  {"name":"dannybrown","artist":"Danny Brown","track":"danny_stop.ogg", "img": "dannybrown.png"},
  {"name":"davidbanner","artist":"David Banner","track":"davidbanner_5.ogg","img":"davidbanner.png"},
  {"name":"desiigner1","artist":"Desiigner","track":"desiigner_pandapanda.ogg","img":"desiigner.png"},
  {"name":"desiigner2","artist":"Desiigner","track":"desiigner_rahhh.ogg","img":"desiigner.png"},
  {"name":"desiigner3","artist":"Desiigner","track":"desiigner_yeha.ogg","img":"desiigner.png"},
  {"name":"diddy","artist":"Diddy","track":"diddy_1.ogg", "img": "diddy.png"},
  {"name":"dizzee","artist":"Dizzee Rascal","track":"dizzee_1.ogg","img":"dizzee.png"},
  {"name":"khaled1","artist":"DJ Khaled","track":"djkhaled_2.ogg","img":"khaled.png"},
  {"name":"khaled2","artist":"DJ Khaled","track":"djkhaled_3.ogg","img":"khaled.png"},
  {"name":"djpaul1","artist":"DJ Paul","track":"djpaul_2.ogg","img":"djpaul.png"},
  {"name":"djpaul2","artist":"DJ Paul","track":"djpaul_3.ogg","img":"djpaul.png"},
  {"name":"djpaul3","artist":"DJ Paul","track":"djpaul_9.ogg","img":"djpaul.png"},
  {"name":"dmx1","artist":"DMX","track":"dmx_1.ogg","img":"dmx.png"},
  {"name":"dmx2","artist":"DMX","track":"dmx_3.ogg","img":"dmx.png"},
  {"name":"dmx3","artist":"DMX","track":"dmx_6.ogg","img":"dmx.png"},
  {"name":"dmx4","artist":"DMX","track":"dmx_7.ogg","img":"dmx.png"},
  {"name":"drake1","artist":"Drake","track":"drake_2.ogg","img":"drake.png"},
  {"name":"drake2","artist":"Drake","track":"drake_3.ogg","img":"drake.png"},
  {"name":"drake3","artist":"Drake","track":"drake_4.ogg","img":"drake.png"},
  {"name":"drake4","artist":"Drake","track":"drake_5.ogg","img":"drake.png"},
  {"name":"drake6","artist":"Drake","track":"drake_worst.ogg","img":"drake.png"},
  {"name":"drummaboy","artist":"Drumma Boy","track":"drummaboy_1.ogg","img":"drummaboy.png"},
  {"name":"e401","artist":"E-40","track":"e40_1.ogg","img":"e40.png"},
  {"name":"e402","artist":"E-40","track":"e40_2.ogg","img":"e40.png"},
  {"name":"eminem1","artist":"Eminem","track":"eminem_3.ogg","img":"eminem.png"},
  {"name":"eminem2","artist":"Eminem","track":"eminem_4.ogg","img":"eminem.png"},
  {"name":"fatjoe1","artist":"Fat Joe","track":"fatjoe_1.ogg","img":"fatjoe.png"},
  {"name":"fatjoe2","artist":"Fat Joe","track":"fatjoe_9.ogg","img":"fatjoe.png"},
  {"name":"fatjoe3","artist":"Fat Joe","track":"fatjoe_5.ogg","img":"fatjoe.png"},
  {"name":"fettywap","artist":"Fetty Wap","track":"fetty_1738.ogg","img":"fetty.png"},
  {"name":"flava","artist":"Flavor Flav","track":"flava_1.ogg","img":"flava.png"},
  {"name":"freeway","artist":"Freeway","track":"freeway_1.ogg","img":"freeway.png"},
  {"name":"frenchie","artist":"French Montana","track":"french_1.ogg","img":"frenchie.png"},
  {"name":"future1","artist":"Future","track":"future_brrr.ogg","img":"future.png"},
  {"name":"future2","artist":"Future","track":"future_hendrix.ogg","img":"future.png"},
  {"name":"future3","artist":"Future","track":"future_hey.ogg","img":"future.png"},
  {"name":"future4","artist":"Future","track":"future_woo.ogg","img":"future.png"},
  {"name":"ghostface","artist":"Ghostface Killah","track":"ghostface_yo.ogg","img":"ghostface.png"},
  {"name":"grandmaster","artist":"Grandmaster Flash","track":"grandmaster_1.ogg","img":"grandmaster.png"},
  {"name":"gucci1","artist":"Gucci Mane","track":"gucci_1.ogg","img":"gucci.png"},
  {"name":"gucci2","artist":"Gucci Mane","track":"gucci_4.ogg","img":"gucci.png"},
  {"name":"gucci3","artist":"Gucci Mane","track":"gucci_14.ogg","img":"gucci.png"},
  {"name":"gucci4","artist":"Gucci Mane","track":"gucci_8.ogg","img":"gucci.png"},
  {"name":"gucci5","artist":"Gucci Mane","track":"gucci_9.ogg","img":"gucci.png"},
  {"name":"hurricane","artist":"Hurricane Chris","track":"hurricanechris_1.ogg","img":"hurricane.png"},
  {"name":"icecube","artist":"Ice Cube","track":"icecube_1.ogg","img":"icecube.png"},
  {"name":"inspectahdeck","artist":"Inspectah Deck","track":"inspectahdeck_killahill.ogg","img":"inspectahdeck.png"},
  {"name":"jadakiss","artist":"Jadakiss","track":"jadakiss_3.ogg","img":"jadakiss.png"},
  {"name":"jarule1","artist":"Ja Rule","track":"jarule_1.ogg","img":"jarule.png"},
  {"name":"jarule2","artist":"Ja Rule","track":"jarule_2.ogg","img":"jarule.png"},
  {"name":"jayz1","artist":"Jay-Z","track":"jayz_7.ogg","img":"jayz.png"},
  {"name":"jayz2","artist":"Jay-Z","track":"jayz_9.ogg","img":"jayz.png"},
  {"name":"jayz3","artist":"Jay-Z","track":"jayz_1.ogg","img":"jayz.png"},
  {"name":"jayz4","artist":"Jay-Z","track":"jayz5.ogg","img":"jayz.png"},
  {"name":"jayz5","artist":"Jay-Z","track":"jayz7.ogg","img":"jayz.png"},
  {"name":"jayz6","artist":"Jay-Z","track":"jayz8.ogg","img":"jayz.png"},
  {"name":"jayz7","artist":"Jay-Z","track":"jayz_itsthero.ogg","img":"jayz.png"},
  {"name":"jayz8","artist":"Jay-Z","track":"jayz_itsyoboy.ogg","img":"jayz.png"},
  {"name":"jayz9","artist":"Jay-Z","track":"jayz_jiggaman.ogg","img":"jayz.png"},
  {"name":"jayz10","artist":"Jay-Z","track":"jayz_woo.ogg","img":"jayz.png"},
  {"name":"jayz11","artist":"Jay-Z","track":"jayz_yessir.ogg","img":"jayz.png"},
  {"name":"jayz12","artist":"Jay-Z","track":"jayz_young.ogg","img":"jayz.png"},
  {"name":"jd","artist":"Jermaine Dupri","track":"jermaine_unh.ogg","img":"jd.png"},
  {"name":"jimjones1","artist":"Jim Jones","track":"jones_8.ogg","img":"jimjones.png"},
  {"name":"jimjones2","artist":"Jim Jones","track":"jones_14.ogg","img":"jimjones.png"},
  {"name":"juelz","artist":"Juelz Santana","track":"juelz_2.ogg","img":"juelz.png"},
  {"name":"juicyj1","artist":"Juicy J","track":"juicyj_1.ogg","img":"juicyj.png"},
  {"name":"juicyj3","artist":"Juicy J","track":"juicyj_9.ogg","img":"juicyj.png"},
  {"name":"juicyj4","artist":"Juicy J","track":"juicyj_10.ogg","img":"juicyj.png"},
  {"name":"kendrick2","artist":"Kendrick Lamar","track":"kendrick_tootoo.ogg","img":"kendrick.png"},
  {"name":"kanye","artist":"Kanye West","track":"kanye_1.ogg","img":"kanye.png"},
  {"name":"killermike1","artist":"Killer Mike","track":"killermike_2.ogg","img":"killermike.png"},
  {"name":"killermike2","artist":"Killer Mike","track":"killermike_3.ogg","img":"killermike.png"},
  {"name":"krsone","artist":"KRS One","track":"krsone_1.ogg","img":"krsone.png"},
  {"name":"lilb1","artist":"Lil B","track":"lilb_1.ogg","img":"lilb.png"},
  {"name":"lilb2","artist":"Lil B","track":"lilb_2.ogg","img":"lilb.png"},
  {"name":"liljon1","artist":"Lil Jon","track":"liljon_2.ogg","img":"liljon.png"},
  {"name":"liljon2","artist":"Lil Jon","track":"liljon_3.ogg","img":"liljon.png"},
  {"name":"lilkim1","artist":"Lil Kim","track":"lilkim_queenb.ogg","img":"lilkim.png"},
  {"name":"lilkim2","artist":"Lil Kim","track":"lilkim_uhunh.ogg","img":"lilkim.png"},
  {"name":"liluzivert","artist":"Lil Uzi Vert","track":"liluzivert_yah2.ogg","img":"liluzivert.png"},
  {"name":"weezy1","artist":"Lil Wayne","track":"weezy_22.ogg","img":"weezy.png"},
  {"name":"weezy2","artist":"Lil Wayne","track":"weezy_25.ogg","img":"weezy.png"},
  {"name":"weezy3","artist":"Lil Wayne","track":"weezy_31.ogg","img":"weezy.png"},
  {"name":"yachty","artist":"Lil Yachty","track":"lilyachty_lilboat.ogg","img":"lilyachty.png"},
  {"name":"ludacris","artist":"Ludacris","track":"ludacris_2.ogg","img":"ludacris.png"},
  {"name":"madeintyo","artist":"Madeintyo","track":"madeintyo_skrrskrr.ogg","img":"madeintyo.png"},
  {"name":"mannie","artist":"Mannie Fresh","track":"mannie_2.ogg","img":"mannie.png"},
  {"name":"mchammer","artist":"MC Hammer","track":"mchammer_1.ogg","img":"mchammer.png"},
  {"name":"methodman","artist":"Method Man","track":"methodman_1.ogg","img":"methodman.png"},
  {"name":"mikejones","artist":"Mike Jones","track":"mikejones_2.ogg","img":"mikejones.png"},
  {"name":"nas","artist":"Nas","track":"nas_6.ogg","img":"nas.png"},
  {"name":"natedogg","artist":"Nate Dogg","track":"natedogg_1.ogg","img":"natedogg.png"},
  {"name":"nicki","artist":"Nicki Minaj","track":"nicki_youngmoney.ogg","img":"nicki.png"},
  {"name":"biggie","artist":"The Notorious B.I.G.","track":"biggie_2.ogg","img":"biggie.png"},
  {"name":"oj","artist":"OJ Da Juiceman","track":"oj_4.ogg","img":"oj.png"},
  {"name":"odb","artist":"Ol Dirty Bastard","track":"odb_shimmy.ogg","img":"odb.png"},
  {"name":"pharrell1","artist":"Pharrell","track":"pharrell_1.ogg","img":"pharrell.png"},
  {"name":"pharrell2","artist":"Pharrell","track":"pharrell_2.ogg","img":"pharrell.png"},
  {"name":"pimpc1","artist":"Pimp C","track":"pimpc_1.ogg","img":"pimpc.png"},
  {"name":"pimpc2","artist":"Pimp C","track":"pimpc_sweetjones3.ogg","img":"pimpc.png"},
  {"name":"pitbull1","artist":"Pitbull","track":"pitbull_1.ogg","img":"pitbull.png"},
  {"name":"pitbull2","artist":"Pitbull","track":"pitbull_2.ogg","img":"pitbull.png"},
  {"name":"pitbull3","artist":"Pitbull","track":"pitbull_6.ogg","img":"pitbull.png"},
  {"name":"projectpat","artist":"Project Pat","track":"projectpat_1.ogg","img":"projectpat.png"},
  {"name":"pushat1","artist":"Pusha T","track":"pushat_1.ogg","img":"pushat.png"},
  {"name":"pushat2","artist":"Pusha T","track":"pushat_haha.ogg","img":"pushat.png"},
  {"name":"pushat3","artist":"Pusha T","track":"pushat_unh.ogg","img":"pushat.png"},
  {"name":"raekwon","artist":"Raekwon","track":"raekwon_yo.ogg","img":"raekwon.png"},
  {"name":"redman","artist":"Redman","track":"redman_heyo.ogg","img":"redman.png"},
  {"name":"ross1","artist":"Rick Ross","track":"ross_1.ogg","img":"ross.png"},
  {"name":"ross2","artist":"Rick Ross","track":"ross_2.ogg","img":"ross.png"},
  {"name":"ross3","artist":"Rick Ross","track":"ross_4.ogg","img":"ross.png"},
  {"name":"ross3","artist":"Rick Ross","track":"ross_woo.ogg","img":"ross.png"},
  {"name":"schoolboyq","artist":"Schoolboy Q","track":"schoolboy_yawk.ogg","img":"schoolboyq.png"},
  {"name":"snoop1","artist":"Snoop Dogg","track":"snoop_5.ogg","img":"snoop.png"},
  {"name":"snoop2","artist":"Snoop Dogg","track":"snoop_4.ogg","img":"snoop.png"},
  {"name":"snoop3","artist":"Snoop Dogg","track":"snoop_1.ogg","img":"snoop.png"},
  {"name":"soulja1","artist":"Soulja Boy","track":"soulja_4.ogg","img":"soulja.png"},
  {"name":"soulja2","artist":"Soulja Boy","track":"soulja_5.ogg","img":"soulja.png"},
  {"name":"swizz","artist":"Swizz Beatz","track":"swizz_1.ogg","img":"swizz.png"},
  {"name":"ti1","artist":"T.I.","track":"ti_5.ogg","img":"ti.png"},
  {"name":"ti2","artist":"T.I.","track":"ti_22.ogg","img":"ti.png"},
  {"name":"tpain1","artist":"T-Pain","track":"tpain_2.ogg", "img":"tpain.png"},
  {"name":"tpain2","artist":"T-Pain","track":"tpain1.ogg","img":"tpain.png"},
  {"name":"treysongz","artist":"Trey Songz","track":"treysongz_4.ogg","img":"treysongz.png"},
  {"name":"trickdaddy1","artist":"Trick Daddy","track":"trick_1.ogg","img":"trickdaddy.png"},
  {"name":"trickdaddy2","artist":"Trick Daddy","track":"trick_2.ogg","img":"trickdaddy.png"},
  {"name":"trickdaddy3","artist":"Trick Daddy","track":"trick_4.ogg","img":"trickdaddy.png"},
  {"name": "twentyonesavage", "artist": "21 Savage", "track": "21savage_21.ogg", "img": "21savage.png"},
  {"name":"tyga","artist":"Tyga","track":"tyga_unh.ogg","img":"tyga.png"},
  {"name":"waka1","artist":"Waka Flocka Flame","track":"waka_1.ogg","img":"waka.png"},
  {"name":"waka2","artist":"Waka Flocka Flame","track":"waka_8.ogg","img":"waka.png"},
  {"name":"willsmith1","artist":"Will Smith","track":"willsmith_1.ogg","img":"willsmith.png"},
  {"name":"willsmith2","artist":"Will Smith","track":"willsmith_2.ogg","img":"willsmith.png"},
  {"name":"wiz1","artist":"Wiz Khalifa","track":"wiz_1.ogg","img":"wiz.png"},
  {"name":"wiz2","artist":"Wiz Khalifa","track":"wiz_unh.ogg","img":"wiz.png"},
  {"name":"jeezy1","artist":"Young Jeezy","track":"jeezy_10.ogg","img":"jeezy.png"},
  {"name":"jeezy3","artist":"Young Jeezy","track":"jeezy_1.ogg","img":"jeezy.png"}
];

export const correctChoice = [
  "That's correct!",
  "Yeaaaaa boyyyy!",
  "YUH",
  "You got it!",
  "Mhm, you know it",
  "Skkrrrrt!",
  "Brraap brraaap!",
  "If ya know ya know!"
]

export const incorrectChoice =[
  "You crazy for this one!",
  "Ouch...",
  "That's wrong! You mad?",
  "Nahhh",
  "That is...not correct.",
  "Ha haaaa! No way!",
  "Mans not hot..."
];

export const colors =['#6D4488',
  '#00727D',
  '#2CB567',
  '#B2BF34',
  '#BCBDCF',
  '#C69A9B',
  '#917B4E',
  '#C14129'
]
export const correctSounds =[
  new Audio('treysongz_4.ogg'),
  new Audio("https://www.myinstants.com/media/sounds/mlg-airhorn.mp3"),
  new Audio('traviscott_yah.ogg'),
  new Audio('yogotti_yeah.ogg')
]
  
  export default NSFW