import React from 'react'
import Navbar from './navbar'



class GameBoard extends React.Component{
  constructor() {
    super()
    this.rappers = [
        {"name":"twochainz","artist":"2 chainz","track":"http://www.therapboard.com/audio/2chainz_yeah2.ogg","img":"http://therapboard.com/images/artist/2chainz.png"},
        {"name":"tupac","artist":"2pac","track":"http://www.therapboard.com/audio/2pac_4.ogg","img":"http://therapboard.com/images/artist/2pac.png"},
        {"name":"fiftycent","artist":"50 Cent","track":"http://www.therapboard.com/audio/50_5.ogg","img":"http://therapboard.com/images/artist/fiftycent.png"},
        {"name":"actionbronson","artist":"Action Bronson","track":"http://www.therapboard.com/audio/action_bronsolino.ogg","img":"http://therapboard.com/images/artist/actionbronson.png"},
        {"name":"akon","artist":"Akon","track":"http://www.therapboard.com/audio/akon_1.ogg","img":"http://therapboard.com/images/artist/akon.png"},
        {"name":"bigboi","artist":"Big Boi","track":"http://www.therapboard.com/audio/bigboi_1.ogg"},
        {"name":"bigsean1","artist":"Big Sean","track":"http://www.therapboard.com/audio/bigsean_boi2.ogg","img":"http://therapboard.com/images/artist/bigsean.png"},
        {"name":"bigsean2","artist":"Big Sean","track":"http://www.therapboard.com/audio/bigsean_holdup2.ogg","img":"http://therapboard.com/images/artist/bigsean.png"},
        {"name":"bigsean3","artist":"Big Sean","track":"http://www.therapboard.com/audio/bigsean_ohgod.ogg","img":"http://therapboard.com/images/artist/bigsean.png"},
        {"name":"birdman1","artist":"Birdman","track":"http://www.therapboard.com/audio/birdman_4.ogg","img":"http://therapboard.com/images/artist/birdman.png"},
        {"name":"birdman2","artist":"Birdman","track":"http://www.therapboard.com/audio/birdman_10.ogg","img":"http://therapboard.com/images/artist/birdman.png"},
        {"name":"bobbyshmurda","artist":"Bobby Shmurda","track":"http://www.therapboard.com/audio/bobby_hahaha.ogg","img":"http://therapboard.com/images/artist/bobby.png"},
        {"name":"bowwow","artist":"Bow Wow","track":"http://www.therapboard.com/audio/bowwow_yeah.ogg","img":"http://therapboard.com/images/artist/bowwow.png"},
        {"name":"bunb","artist":"Bun B","track":"http://www.therapboard.com/audio/bunb_ugk4life.ogg","img":"http://therapboard.com/images/artist/bunb.png"},
        {"name":"busta","artist":"Busta Rhymes","track":"http://www.therapboard.com/audio/busta_6.ogg","img":"http://therapboard.com/images/artist/busta.png"},
        {"name":"camron","artist":"Cam'Ron","track":"http://www.therapboard.com/audio/camron_1.ogg","img":"http://therapboard.com/images/artist/camron.png"},
        {"name":"chance","artist":"Chance The Rapper","track":"http://www.therapboard.com/audio/chance_aghh2.ogg","img":"http://therapboard.com/images/artist/chance.png"},
        {"name":"chingy","artist":"Chingy","track":"http://www.therapboard.com/audio/chingy_1.ogg"},
        {"name":"currensy","artist":"Curren$y","track":"http://www.therapboard.com/audio/currensy_1.ogg"},
        {"name":"dabrat","artist":"Da Brat","track":"http://www.therapboard.com/audio/dabrat_comeon.ogg"},
        {"name":"dabrat","artist":"Da Brat","track":"http://www.therapboard.com/audio/dabrat_lookout.ogg"},
        {"name":"dabrat","artist":"Da Brat","track":"http://www.therapboard.com/audio/dabrat_oh.ogg"},
        {"name":"dannybrown","artist":"Danny Brown","track":"http://www.therapboard.com/audio/danny_stop.ogg", "img": "http://therapboard.com/images/artist/dannybrown.png"},
        {"name":"davidbanner","artist":"David Banner","track":"http://www.therapboard.com/audio/davidbanner_5.ogg"},
        {"name":"diddy","artist":"Diddy","track":"http://www.therapboard.com/audio/diddy_1.ogg", "img": "http://therapboard.com/images/artists/diddy.png"},
        {"name":"dizzee","artist":"Dizzee Rascal","track":"http://www.therapboard.com/audio/dizzee_1.ogg"},
        {"name":"khaled","artist":"DJ Khaled","track":"http://www.therapboard.com/audio/djkhaled_2.ogg"},
        {"name":"khaled","artist":"DJ Khaled","track":"http://www.therapboard.com/audio/djkhaled_3.ogg"},
        {"name":"djpaul","artist":"DJ Paul","track":"http://www.therapboard.com/audio/djpaul_2.ogg"},
        {"name":"djpaul","artist":"DJ Paul","track":"http://www.therapboard.com/audio/djpaul_3.ogg"},
        {"name":"djpaul","artist":"DJ Paul","track":"http://www.therapboard.com/audio/djpaul_9.ogg"},
        {"name":"dmx","artist":"DMX","track":"http://www.therapboard.com/audio/dmx_1.ogg"},
        {"name":"dmx","artist":"DMX","track":"http://www.therapboard.com/audio/dmx_3.ogg"},
        {"name":"dmx","artist":"DMX","track":"http://www.therapboard.com/audio/dmx_6.ogg"},
        {"name":"dmx","artist":"DMX","track":"http://www.therapboard.com/audio/dmx_7.ogg"},
        {"name":"drake","artist":"Drake","track":"http://www.therapboard.com/audio/drake_2.ogg"},
        {"name":"drake","artist":"Drake","track":"http://www.therapboard.com/audio/drake_3.ogg"},
        {"name":"drake","artist":"Drake","track":"http://www.therapboard.com/audio/drake_4.ogg"},
        {"name":"drake","artist":"Drake","track":"http://www.therapboard.com/audio/drake_5.ogg"},
        {"name":"drummaboy","artist":"Drumma Boy","track":"http://www.therapboard.com/audio/drummaboy_1.ogg"},
        {"name":"e40","artist":"E-40","track":"http://www.therapboard.com/audio/e40_1.ogg"},
        {"name":"e40","artist":"E-40","track":"http://www.therapboard.com/audio/e40_2.ogg"},
        {"name":"eazye","artist":"Eazy-E","track":"http://www.therapboard.com/audio/eazye_1.ogg"},
        {"name":"eminem","artist":"Eminem","track":"http://www.therapboard.com/audio/eminem_3.ogg"},
        {"name":"eminem","artist":"Eminem","track":"http://www.therapboard.com/audio/eminem_4.ogg"},
        {"name":"fatjoe","artist":"Fat Joe","track":"http://www.therapboard.com/audio/fatjoe_1.ogg"},
        {"name":"fatjoe","artist":"Fat Joe","track":"http://www.therapboard.com/audio/fatjoe_9.ogg"},
        {"name":"fatjoe","artist":"Fat Joe","track":"http://www.therapboard.com/audio/fatjoe_5.ogg"},
        {"name":"flava","artist":"Flavor Flav","track":"http://www.therapboard.com/audio/flava_1.ogg"},
        {"name":"freeway","artist":"Freeway","track":"http://www.therapboard.com/audio/freeway_1.ogg"},
        {"name":"frenchie","artist":"French Montana","track":"http://www.therapboard.com/audio/french_1.ogg"},
        {"name":"ghostface","artist":"Ghostface Killah","track":"http://www.therapboard.com/audio/ghostface_yo.ogg"},
        {"name":"grandmaster","artist":"Grandmaster Flash","track":"http://www.therapboard.com/audio/grandmaster_1.ogg"},
        {"name":"gucci","artist":"Gucci Mane","track":"http://www.therapboard.com/audio/gucci_1.ogg"},
        {"name":"gucci","artist":"Gucci Mane","track":"http://www.therapboard.com/audio/gucci_4.ogg"},
        {"name":"gucci","artist":"Gucci Mane","track":"http://www.therapboard.com/audio/gucci_14.ogg"},
        {"name":"gucci","artist":"Gucci Mane","track":"http://www.therapboard.com/audio/gucci_8.ogg"},
        {"name":"gucci","artist":"Gucci Mane","track":"http://www.therapboard.com/audio/gucci_9.ogg"},
        {"name":"hurricane","artist":"Hurricane Chris","track":"http://www.therapboard.com/audio/hurricanechris_1.ogg"},
        {"name":"icecube","artist":"Ice Cube","track":"http://www.therapboard.com/audio/icecube_1.ogg"},
        {"name":"inspectahdeck","artist":"Inspctah Deck","track":"http://www.therapboard.com/audio/inspectahdeck_killahill.ogg"},
        {"name":"jadakiss","artist":"Jadakiss","track":"http://www.therapboard.com/audio/jadakiss_3.ogg"},
        {"name":"jarule","artist":"Ja Rule","track":"http://www.therapboard.com/audio/jarule_1.ogg"},
        {"name":"jarule","artist":"Ja Rule","track":"http://www.therapboard.com/audio/jarule_2.ogg"},
        {"name":"jayz","artist":"Jay-Z","track":"http://www.therapboard.com/audio/jayz_7.ogg"},
        {"name":"jayz","artist":"Jay-Z","track":"http://www.therapboard.com/audio/jayz_9.ogg"},
        {"name":"jayz","artist":"Jay-Z","track":"http://www.therapboard.com/audio/jayz_1.ogg"},
        {"name":"jayz","artist":"Jay-Z","track":"http://www.therapboard.com/audio/jayz5.ogg"},
        {"name":"jayz","artist":"Jay-Z","track":"http://www.therapboard.com/audio/jayz7.ogg"},
        {"name":"jayz","artist":"Jay-Z","track":"http://www.therapboard.com/audio/jayz8.ogg"},
        {"name":"jayz","artist":"Jay-Z","track":"http://www.therapboard.com/audio/jayz_itsthero.ogg"},
        {"name":"jayz","artist":"Jay-Z","track":"http://www.therapboard.com/audio/jayz_itsyoboy.ogg"},
        {"name":"jayz","artist":"Jay-Z","track":"http://www.therapboard.com/audio/jayz_jiggaman.ogg"},
        {"name":"jayz","artist":"Jay-Z","track":"http://www.therapboard.com/audio/jayz_woo.ogg"},
        {"name":"jayz","artist":"Jay-Z","track":"http://www.therapboard.com/audio/jayz_yessir.ogg"},
        {"name":"jayz","artist":"Jay-Z","track":"http://www.therapboard.com/audio/jayz_young.ogg"},
        {"name":"jazzypha","artist":"Jazzy Phae","track":"http://www.therapboard.com/audio/jazzypha_1.ogg"},
        {"name":"jd","artist":"Jermaine Dupri","track":"http://www.therapboard.com/audio/jermaine_unh.ogg"},
        {"name":"jimjones","artist":"Jim Jones","track":"http://www.therapboard.com/audio/jones_8.ogg"},
        {"name":"jimjones","artist":"Jim Jones","track":"http://www.therapboard.com/audio/jones_14.ogg"},
        {"name":"juelz","artist":"Juelz Santana","track":"http://www.therapboard.com/audio/juelz_2.ogg"},
        {"name":"juicyj","artist":"Juicy J","track":"http://www.therapboard.com/audio/juicyj_1.ogg"},
        {"name":"juicyj","artist":"Juicy J","track":"http://www.therapboard.com/audio/juicyj_8.ogg"},
        {"name":"juicyj","artist":"Juicy J","track":"http://www.therapboard.com/audio/juicyj_9.ogg"},
        {"name":"juicyj","artist":"Juicy J","track":"http://www.therapboard.com/audio/juicyj_10.ogg"},
        {"name":"juicyj","artist":"Juicy J","track":"http://www.therapboard.com/audio/juicyj_7.ogg"},
        {"name":"kanye","artist":"Kanye West","track":"http://www.therapboard.com/audio/kanye_1.ogg"},
        {"name":"killermike","artist":"Killer Mike","track":"http://www.therapboard.com/audio/killermike_2.ogg"},
        {"name":"killermike","artist":"Killer Mike","track":"http://www.therapboard.com/audio/killermike_3.ogg"},
        {"name":"krsone","artist":"KRS One","track":"http://www.therapboard.com/audio/krsone_1.ogg"},
        {"name":"lilb","artist":"Lil B","track":"http://www.therapboard.com/audio/lilb_1.ogg"},
        {"name":"lilb","artist":"Lil B","track":"http://www.therapboard.com/audio/lilb_2.ogg"},
        {"name":"liljon","artist":"Lil Jon","track":"http://www.therapboard.com/audio/liljon_2.ogg"},
        {"name":"liljon","artist":"Lil Jon","track":"http://www.therapboard.com/audio/liljon_3.ogg"},
        {"name":"liljon","artist":"Lil Jon","track":"http://www.therapboard.com/audio/liljon_8.ogg"},
        {"name":"liljon","artist":"Lil Jon","track":"http://www.therapboard.com/audio/liljon_4.ogg"},
        {"name":"lilscrappy","artist":"Lil Scrappy","track":"http://www.therapboard.com/audio/lilscrappy_1.ogg"},
        {"name":"weezy","artist":"Lil Wayne","track":"http://www.therapboard.com/audio/weezy_14.ogg"},
        {"name":"weezy","artist":"Lil Wayne","track":"http://www.therapboard.com/audio/weezy_22.ogg"},
        {"name":"weezy","artist":"Lil Wayne","track":"http://www.therapboard.com/audio/weezy_29.ogg"},
        {"name":"weezy","artist":"Lil Wayne","track":"http://www.therapboard.com/audio/weezy_4.ogg"},
        {"name":"weezy","artist":"Lil Wayne","track":"http://www.therapboard.com/audio/weezy_16.ogg"},
        {"name":"weezy","artist":"Lil Wayne","track":"http://www.therapboard.com/audio/weezy_17.ogg"},
        {"name":"weezy","artist":"Lil Wayne","track":"http://www.therapboard.com/audio/weezy_25.ogg"},
        {"name":"weezy","artist":"Lil Wayne","track":"http://www.therapboard.com/audio/weezy_30.ogg"},
        {"name":"weezy","artist":"Lil Wayne","track":"http://www.therapboard.com/audio/weezy_31.ogg"},
        {"name":"lloydbanks","artist":"Lloyd Banks","track":"http://www.therapboard.com/audio/banks_unh.ogg"},
        {"name":"lloydbanks","artist":"Lloyd Banks","track":"http://www.therapboard.com/audio/banks_yeah.ogg"},
        {"name":"ludacris","artist":"Ludacris","track":"http://www.therapboard.com/audio/ludacris_2.ogg"},
        {"name":"ludacris","artist":"Ludacris","track":"http://www.therapboard.com/audio/ludacris_woo.ogg"},
        {"name":"mannie","artist":"Mannie Fresh","track":"http://www.therapboard.com/audio/mannie_1.ogg"},
        {"name":"mannie","artist":"Mannie Fresh","track":"http://www.therapboard.com/audio/mannie_2.ogg"},
        {"name":"mceight","artist":"MC Eiht","track":"http://www.therapboard.com/audio/mceiht_1.ogg"},
        {"name":"mchammer","artist":"MC Hammer","track":"http://www.therapboard.com/audio/mchammer_1.ogg"},
        {"name":"methodman","artist":"Method Man","track":"http://www.therapboard.com/audio/methodman_1.ogg"},
        {"name":"methodman","artist":"Method Man","track":"http://www.therapboard.com/audio/methodman_tical.ogg"},
        {"name":"methodman","artist":"Method Man","track":"http://www.therapboard.com/audio/methodman_yo.ogg"},
        {"name":"mikejones","artist":"Mike Jones","track":"http://www.therapboard.com/audio/mikejones_2.ogg"},
        {"name":"mikejones","artist":"Mike Jones","track":"http://www.therapboard.com/audio/mikejones_iceage.ogg"},
        {"name":"mikejones","artist":"Mike Jones","track":"http://www.therapboard.com/audio/mikejones_jyeah.ogg"},
        {"name":"mop","artist":"M.O.P.","track":"http://www.therapboard.com/audio/mop_1.ogg"},
        {"name":"mop","artist":"M.O.P.","track":"http://www.therapboard.com/audio/mop_2.ogg"},
        {"name":"nas","artist":"Nas","track":"http://www.therapboard.com/audio/nas_1.ogg"},
        {"name":"nas","artist":"Nas","track":"http://www.therapboard.com/audio/nas_3.ogg"},
        {"name":"nas","artist":"Nas","track":"http://www.therapboard.com/audio/nas_6.ogg"},
        {"name":"natedogg","artist":"Nate Dogg","track":"http://www.therapboard.com/audio/natedogg_1.ogg"},
        {"name":"nicki","artist":"Nicki Minaj","track":"http://www.therapboard.com/audio/nicki_youngmoney.ogg","img":"http://therapboard.com/images/artist/nicki.png"},
        {"name":"biggie","artist":"The Notorious B.I.G.","track":"http://www.therapboard.com/audio/biggie_1.ogg"},
        {"name":"biggie","artist":"The Notorious B.I.G.","track":"http://www.therapboard.com/audio/biggie_2.ogg"},
        {"name":"oj","artist":"OJ Da Juiceman","track":"http://www.therapboard.com/audio/oj_4.ogg"},
        {"name":"odb","artist":"Ol Dirty Bastard","track":"http://www.therapboard.com/audio/odb_shimmy.ogg"},
        {"name":"odb","artist":"Ol Dirty Bastard","track":"http://www.therapboard.com/audio/odb_yo.ogg"},
        {"name":"pharrell","artist":"Pharrell","track":"http://www.therapboard.com/audio/pharrell_1.ogg"},
        {"name":"pharrell","artist":"Pharrell","track":"http://www.therapboard.com/audio/pharrell_2.ogg"},
        {"name":"pill","artist":"Pill","track":"http://www.therapboard.com/audio/pill_1.ogg"},
        {"name":"pimpc","artist":"Pimp C","track":"http://www.therapboard.com/audio/pimpc_4.ogg"},
        {"name":"pimpc","artist":"Pimp C","track":"http://www.therapboard.com/audio/pimpc_1.ogg"},
        {"name":"pimpc","artist":"Pimp C","track":"http://www.therapboard.com/audio/pimpc_sweetjones3.ogg"},
        {"name":"pitbull","artist":"Pitbull","track":"http://www.therapboard.com/audio/pitbull_1.ogg"},
        {"name":"pitbull","artist":"Pitbull","track":"http://www.therapboard.com/audio/pitbull_2.ogg"},
        {"name":"pitbull","artist":"Pitbull","track":"http://www.therapboard.com/audio/pitbull_3.ogg"},
        {"name":"pitbull","artist":"Pitbull","track":"http://www.therapboard.com/audio/pitbull_6.ogg"},
        {"name":"projectpat","artist":"Project Pat","track":"http://www.therapboard.com/audio/projectpat_1.ogg"},
        {"name":"pushat","artist":"Pusha T","track":"http://www.therapboard.com/audio/pushat_1.ogg"},
        {"name":"pushat","artist":"Pusha T","track":"http://www.therapboard.com/audio/pushat_haha.ogg"},
        {"name":"pushat","artist":"Pusha T","track":"http://www.therapboard.com/audio/pushat_unh.ogg"},
        {"name":"raekwon","artist":"Raekwon","track":"http://www.therapboard.com/audio/raekwon_yo.ogg"},
        {"name":"redman","artist":"Redman","track":"http://www.therapboard.com/audio/redman_heyo.ogg"},
        {"name":"ross","artist":"Rick Ross","track":"http://www.therapboard.com/audio/ross_1.ogg"},
        {"name":"ross","artist":"Rick Ross","track":"http://www.therapboard.com/audio/ross_2.ogg"},
        {"name":"ross","artist":"Rick Ross","track":"http://www.therapboard.com/audio/ross_4.ogg"},
        {"name":"ross","artist":"Rick Ross","track":"http://www.therapboard.com/audio/ross_woo.ogg"},
        {"name":"snoop","artist":"Snoop Dogg","track":"http://www.therapboard.com/audio/snoop_5.ogg"},
        {"name":"snoop","artist":"Snoop Dogg","track":"http://www.therapboard.com/audio/snoop_4.ogg"},
        {"name":"snoop","artist":"Snoop Dogg","track":"http://www.therapboard.com/audio/snoop_1.ogg"},
        {"name":"soulja1","artist":"Soulja Boy","track":"http://www.therapboard.com/audio/soulja_4.ogg","img":"http://therapboard.com/images/artist/soulja.png"},
        {"name":"soulja2","artist":"Soulja Boy","track":"http://www.therapboard.com/audio/soulja_5.ogg","img":"http://therapboard.com/images/artist/soulja.png"},
        {"name":"swizz","artist":"Swizz Beatz","track":"http://www.therapboard.com/audio/swizz_1.ogg","img":"http://therapboard.com/images/artist/swizz.png"},
        {"name":"ti1","artist":"T.I.","track":"http://www.therapboard.com/audio/ti_5.ogg","img":"http://therapboard.com/images/artist/ti.png"},
        {"name":"ti2","artist":"T.I.","track":"http://www.therapboard.com/audio/ti_22.ogg","img":"http://therapboard.com/images/artist/ti.png"},
        {"name":"tpain1","artist":"T-Pain","track":"http://www.therapboard.com/audio/tpain_2.ogg", "img":"http://therapboard.com/images/artist/tpain.png"},
        {"name":"tpain2","artist":"T-Pain","track":"http://www.therapboard.com/audio/tpain1.ogg","img":"http://therapboard.com/images/artist/tpain.png"},
        {"name":"treysongz","artist":"Trey Songz","track":"http://www.therapboard.com/audio/treysongz_4.ogg","img":"http://therapboard.com/images/artist/treysongz.png"},
        {"name":"trickdaddy","artist":"Trick Daddy","track":"http://www.therapboard.com/audio/trick_1.ogg"},
        {"name":"trickdaddy","artist":"Trick Daddy","track":"http://www.therapboard.com/audio/trick_2.ogg"},
        {"name":"trickdaddy","artist":"Trick Daddy","track":"http://www.therapboard.com/audio/trick_4.ogg"},
        {"name": "twentyonesavage", "artist": "21 Savage", "track": "http://www.therapboard.com/audio/21savage_21.ogg", "img": "http://therapboard.com/images/artist/21savage.png"},
        {"name":"tyga","artist":"Tyga","track":"http://www.therapboard.com/audio/tyga_unh.ogg"},
        {"name":"waka","artist":"Waka Flocka Flame","track":"http://www.therapboard.com/audio/waka_1.ogg"},
        {"name":"waka","artist":"Waka Flocka Flame","track":"http://www.therapboard.com/audio/waka_8.ogg"},
        {"name":"willsmith","artist":"Will Smith","track":"http://www.therapboard.com/audio/willsmith_1.ogg"},
        {"name":"willsmith","artist":"Will Smith","track":"http://www.therapboard.com/audio/willsmith_2.ogg"},
        {"name":"willsmith","artist":"Will Smith","track":"http://www.therapboard.com/audio/willsmith_3.ogg"},
        {"name":"wiz","artist":"Wiz Khalifa","track":"http://www.therapboard.com/audio/wiz_1.ogg"},
        {"name":"wiz","artist":"Wiz Khalifa","track":"http://www.therapboard.com/audio/wiz_unh.ogg"},
        {"name":"jeezy","artist":"Young Jeezy","track":"http://www.therapboard.com/audio/jeezy_10.ogg"},
        {"name":"jeezy","artist":"Young Jeezy","track":"http://www.therapboard.com/audio/jeezy_11.ogg"},
        {"name":"jeezy","artist":"Young Jeezy","track":"http://www.therapboard.com/audio/jeezy_1.ogg"}
      ]
  }
  render() {
    return (
    <div>
      <div>
         <Navbar />
      </div>
<div id='rappers'>
      {
        this.rappers.map(rapper => (
          <figure key={rapper.name}> 
            <img id= {rapper.name} src={rapper.img ? rapper.img : 'http://therapboard.com/images/artist/21savage.png'} />
            <figcaption><h4>{rapper.artist}</h4></figcaption>
            </figure>
        ))
      }
</div>
      <button type='button'id='button'>Play!</button>
  </div>
    )
  }

}

export default GameBoard